### ISSUE TITLE
i got Error While Installing

### ISSUE THREAD

**Issue by mehranexpert** [securestate/king-phisher#118]
```
root@5f2558e0be72:/opt/king-phisher/tools#

 ./install.sh
Linux version detected as Kali
Install and use PostgreSQL? (Highly recommended and required for upgrading) [Y/n] y
Will install and configure PostgreSQL for the server
Attempting to update apt-get cache pacakge information
Hit:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease
Hit:2 http://ftp.halifax.rwth-aachen.de/kali sana InRelease
Reading package lists... Done
Git repo found at /opt/king-phisher
Checking Kali 2 apt sources
Installing Kali dependencies
Reading package lists... Done
Building dependency tree
Reading state information... Done
libfreetype6-dev is already the newest version (2.6.3-3+b1).
python-dev is already the newest version (2.7.11-2).
python-pip is already the newest version (8.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
gir1.2-gtk-3.0 is already the newest version (3.20.6-1).
gir1.2-gtksource-3.0 is already the newest version (3.20.3-1).
gir1.2-webkit-3.0 is already the newest version (2.4.11-1+b1).
libgeos++-dev is already the newest version (3.5.0-3).
libgtk-3-dev is already the newest version (3.20.6-1).
libpq-dev is already the newest version (9.5.3-1).
pkg-config is already the newest version (0.29-4).
python-cairo is already the newest version (1.8.8-2).
python-gi is already the newest version (3.20.1-1).
python-gi-cairo is already the newest version (3.20.1-1).
python-gobject is already the newest version (3.20.1-1).
python-gobject-dev is already the newest version (3.20.1-1).
python-paramiko is already the newest version (1.16.0-1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
gir1.2-vte-2.91 - GObject introspection data for the VTE library
Reading package lists... Done
Building dependency tree
Reading state information... Done
gir1.2-vte-2.91 is already the newest version (0.44.2-1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Failed to install gir1.2-webkit2-3.0 with apt-get
Searching for distribute
Reading https://pypi.python.org/simple/distribute/
Best match: distribute 0.7.3
Processing distribute-0.7.3-py2.7.egg
distribute 0.7.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/distribute-0.7.3-py2.7.egg
Processing dependencies for distribute
Finished processing dependencies for distribute
Installing Python package dependencies from PyPi
Requirement already up-to-date: pip in /usr/lib/python2.7/dist-packages
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: six in /usr/lib/python2.7/dist-packages
Ignoring dnspython3: markers u"python_version >= '3.0'" don't match your environment
Collecting advancedhttpserver==1.2.0 (from -r requirements.txt (line 3))
  Using cached AdvancedHTTPServer-1.2.0.tar.gz
Collecting alembic>=0.8.5 (from -r requirements.txt (line 4))
  Using cached alembic-0.8.6.tar.gz
Collecting boltons>=16.1.1 (from -r requirements.txt (line 5))
  Using cached boltons-16.4.1-py2.py3-none-any.whl
Collecting dnspython>=1.12.0 (from -r requirements.txt (line 6))
  Using cached dnspython-1.14.0.zip
Collecting geoip2>=2.2.0 (from -r requirements.txt (line 8))
  Using cached geoip2-2.4.0-py2.py3-none-any.whl
Collecting geojson>=1.3.2 (from -r requirements.txt (line 9))
  Using cached geojson-1.3.2-py2.py3-none-any.whl
Collecting icalendar>=3.9.2 (from -r requirements.txt (line 10))
  Using cached icalendar-3.10.tar.gz
Collecting ipaddress>=1.0.16 (from -r requirements.txt (line 11))
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting Jinja2>=2.8 (from -r requirements.txt (line 12))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting markupsafe>=0.23 (from -r requirements.txt (line 13))
  Using cached MarkupSafe-0.23.tar.gz
Collecting matplotlib>=1.5.1 (from -r requirements.txt (line 14))
  Downloading matplotlib-1.5.1.tar.gz (54.0MB)
    99% |############################### | 54.0MB 29.0MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 563, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 552, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/serialize.py", line 49, in dumps
    "body": _b64_encode_bytes(body),
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
  File "/usr/lib/python2.7/base64.py", line 54, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
MemoryError
Failed to install python requirements with pip
root@5f2558e0be72:/opt/king-phisher/tools#
```

**Comment by guitarmanj** [comment]
Hey there,

try taking matplotlib out of the requirements.txt file, then running 'apt-get install -y python-matplotlib'

Rerun the install file.


Thanks!


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by wolfthefallen** [comment]
Hi @mehranexpert ,

Please comment metplotlib out of the requirments file, and then install it manually either via 


```
# I recommend this method
pip --no-cache-dir install matplotlib
```

or 

```
apt-get install -y python-matplotlib
```

Then rerun the installl.sh script from the tools directory.

**Comment by zeroSteiner** [comment]
The memory error can also be gotten around by giving more RAM to your VM.

**Comment by mehranexpert** [comment]
Thanks @guitarmanj  and @wolfthefallen that is worked , now another issue **Starting the King Phisher service**

```
Updating the GTK icon cache
gtk-update-icon-cache: Cache file created successfully.
Successfully installed basemap with pip
Configuring the PostgreSQL server
PostgreSQL configuration file found at /etc/postgresql/9.5/main/pg_hba.conf
Installing the King Phisher systemd service file in /lib/systemd/system/
Starting the King Phisher service
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory

```

**Comment by zeroSteiner** [comment]
Looks like a problem relating to systemd.

**Comment by zeroSteiner** [comment]
Can you post the output of the command: `systemctl status dbus.service`.

**Comment by mehranexpert** [comment]
```
:/opt/king-phisher/tools# systemctl status dbus.service
Failed to connect to bus: No such file or directory
```

**Comment by zeroSteiner** [comment]
Are you using the King Phisher supplied Docker container or attempting to install it in your own container? We have one that is available for the latest release in which it's already installed. There's details in the [Docker wiki](https://github.com/securestate/king-phisher/wiki/Docker) page on how to set it up.

**Comment by mehranexpert** [comment]
i didn't know it have Container ,  i don't fine link in wiki to pull Container , anyway i search on docker and find  [https://hub.docker.com/u/securestate/](Docker)   , im Pull [https://hub.docker.com/r/securestate/king-phisher-server/](king-phisher-server) 

i dont see any open ports on this Container `CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                                                                NAMES
a33c5a4c8c5d        securestate/king-phisher-server   "/bin/bash"              4 minutes ago       Up 4 minutes              `

am i Pull it Right ?  in wiki it said Navigate to `/data/server/docker`     but that Container Does not have Data ..

`root@a33c5a4c8c5d:/# ls
bin  boot  config  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
`

**Comment by mehranexpert** [comment]
oh good it have own Container i didn't know this , i pull it but i dont see any Ports (80 and 4022) on my Container
`
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                                                                NAMES
a33c5a4c8c5d        securestate/king-phisher-server   "/bin/bash"              About an hour ago   Up About an hour                
`

**Comment by zeroSteiner** [comment]
There's a page in the wiki titled Docker. Read it carefully and follow the instructions.

**Comment by mehranexpert** [comment]
yes i did all on Wiki , but i got error 
`root@91ab53e64dd3:/opt/king-phisher/data/server/docker# docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.`

**Comment by mehranexpert** [comment]
that wiki is not so clear , i pull that two images from docker  ,  i enter to Container `securestate/king-phisher-server `

now in that image `Docker `not installed , am i should install `docker `on `securestate/king-phisher-server`

i try [https://docs.docker.com/engine/installation/linux/ubuntulinux/](url) to install `Docker` on `Container  `
`securestate/king-phisher-server `

**Comment by zeroSteiner** [comment]
Exactly what part of the wiki isn't clear? You shouldn't need to install Docker in the container. 

@wolfthefallen can you please take a look at this, you're a bit more versed in the Docker setup.

**Comment by wolfthefallen** [comment]
@mehranexpert

please provide me the out put of the following. Please blur out any public IP addresses and passwords in the output. This will give me the information to help you troubleshoot your issue.

```
# from king-phisher/data/server/docker
sudo docker-composer up -d
sudo ifconfig
sudo netstat -untap
docker -v
docker-compose -v
```

**Comment by mehranexpert** [comment]
at the end i success install it , Please update wiki that `Navigate to /data/server/docker` to 

> First git clone king-phisher from repository and then Navigate to /data/server/docker

**Comment by zeroSteiner** [comment]
I think you're trying to say that you were able to successfully install it, so I'm going to close this issue. Thanks for the update and I'll add the note to the wiki.
