### ISSUE TITLE
Issues with importing smoke_zephyr

### ISSUE THREAD

**Issue by DigiAngel** [securestate/king-phisher#151]
## Issue Description
Seems unable to import smoke_zephyr

## Reproduction Steps
Attempt to run KingPhisher with ./KingPhiher in /opt/king-phisher

## Environment Details
Host OS: Ubuntu 16.04.1, PowerPC <- maybe testing on PowerPC isn't a good idea....

## Error Details / Stack Trace
~~~
powerbook:/opt/king-phisher$] ./KingPhisher
Traceback (most recent call last):
  File "./KingPhisher", line 44, in <module>
    from king_phisher import color
  File "/opt/king-phisher/king_phisher/__init__.py", line 33, in <module>
    from . import version
  File "/opt/king-phisher/king_phisher/version.py", line 37, in <module>
    import smoke_zephyr.utilities
ImportError: No module named smoke_zephyr.utilities
~~~

additional info:
~~~
[11:01:17 powerbook:/opt/king-phisher$] sudo pip install --upgrade smoke_zephyr
Requirement already up-to-date: smoke_zephyr in /usr/local/lib/python3.5/dist-packages

[11:01:28 powerbook:/opt/king-phisher$] locate smoke_zephyr
/usr/local/lib/python3.5/dist-packages/smoke_zephyr
/usr/local/lib/python3.5/dist-packages/smoke_zephyr-1.1.0-py3.5.egg-info
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__init__.py
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__pycache__
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/argparse_types.py
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/configuration.py
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/job.py
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/requirements.py
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/utilities.py
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__pycache__/__init__.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__pycache__/argparse_types.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__pycache__/configuration.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__pycache__/job.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__pycache__/requirements.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/smoke_zephyr/__pycache__/utilities.cpython-35.pyc
/usr/local/lib/python3.5/dist-packages/smoke_zephyr-1.1.0-py3.5.egg-info/PKG-INFO
/usr/local/lib/python3.5/dist-packages/smoke_zephyr-1.1.0-py3.5.egg-info/SOURCES.txt
/usr/local/lib/python3.5/dist-packages/smoke_zephyr-1.1.0-py3.5.egg-info/dependency_links.txt
/usr/local/lib/python3.5/dist-packages/smoke_zephyr-1.1.0-py3.5.egg-info/installed-files.txt
/usr/local/lib/python3.5/dist-packages/smoke_zephyr-1.1.0-py3.5.egg-info/top_level.txt
~~~

Thank you...let me know if I should be testing an a different architecture and I'll switch to a VM.

**Comment by zeroSteiner** [comment]
New installations are using Python3  now. You'll want to run King Phisher with `python3 ./KingPhisher` if you're going to start it from the command line. We won't update the she-bang line until more users have converted to Python3.

You'll also want to ensure that smoke-zephyr is installed with Python3 using `python3 -m pip install -r requirements.txt`.

**Comment by DigiAngel** [comment]
Thank you...that seems to have fixed it up.  Continuing on with testing!
