### ISSUE TITLE
Error when configuring king-phisher to use postgresql in Kali

### ISSUE THREAD

**Issue by silasbarnes** [securestate/king-phisher#17]
################################################################
uname -a = Linux shad0wlyte 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

pg_hba.conf = /etc/postgresql/9.1/main/pg_hba.conf

Installed via 'wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && sudo bash ./install.sh' method.
################################################################

Using SQLite works a treat, no dramas there. 

Made configuration changes to enable Postgresql support as described here: https://github.com/securestate/king-phisher/wiki/Database step by step.

Postgresql user created, pg_hba.conf edited, server_config.yml modified as described and services restarted. Rebooted system just in case. 

Error follows:

root@shad0w:/opt/king-phisher# /opt/king-phisher/KingPhisherServer -L INFO -f /opt/king-phisher/server_config.yml
Traceback (most recent call last):
  File "/opt/king-phisher/KingPhisherServer", line 205, in <module>
    sys.exit(main())
  File "/opt/king-phisher/KingPhisherServer", line 98, in main
    config = configuration.Configuration(config_file.name)
  File "/opt/king-phisher/king_phisher/configuration.py", line 70, in __init__
    self._storage = dict(self._serializer('load', file_h))
  File "/opt/king-phisher/king_phisher/configuration.py", line 84, in _serializer
    return function(*args)
  File "/opt/king-phisher/king_phisher/configuration.py", line 54, in <lambda>
    SERIALIZER_DRIVERS['yml'] = {'load': lambda file_obj: yaml.load(file_obj, Loader=Loader), 'dumps': lambda obj: yaml.dumps(obj, default_flow_style=False, Dumper=Dumper)}
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:7622)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:7883)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:8571)
  File "_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10132)
  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:10310)
yaml.parser.ParserError: while parsing a block mapping
  in "/opt/king-phisher/server_config.yml", line 5, column 1
did not find expected key
  in "/opt/king-phisher/server_config.yml", line 32, column 3

Triple checked passwords, all looks to be in order. Googled extensively in an attempt not to waste anyone's time. Any help very much appreciated.

Silas

Silas

**Comment by zeroSteiner** [comment]
The error doesn't necessarily look like it's related to postgres being used. From the stack trace, it looks like the configuration file might be malformed. I'll see if I can reproduce this later today. Would you be able to post the contents of the server configuration in the meantime?

**Comment by silasbarnes** [comment]
I'm an idiot. The postgresql configuration line in server_config.yml was not indented correctly. Apologies for wasting your time Spencer, and thanks again.

Silas

**Comment by zeroSteiner** [comment]
It's no problem it got me looking into better error handling so the parsing error message will be more clear in the future.
