### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by jgoody** [securestate/king-phisher#181]
## Issue Description
 sudo python /opt/king-phisher/KingPhisherServer -L INFO -f server_config.yml
WARNING  python 2.7 support is deprecated, see https://github.com/securestate/king-phisher/wiki/Python-3 for details
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver sqlite
Traceback (most recent call last):
  File "/opt/king-phisher/KingPhisherServer", line 238, in <module>
    sys.exit(main())
  File "/opt/king-phisher/KingPhisherServer", line 232, in main
    status_code = build_and_run(arguments, config, plugin_manager)
  File "/opt/king-phisher/KingPhisherServer", line 91, in build_and_run
    king_phisher_server = build.server_from_config(config, plugin_manager=plugin_manager)
  File "/opt/king-phisher/king_phisher/server/build.py", line 159, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 746, in __init__
    self.database_engine = db_manager.init_database(config.get('server.database'), extra_init=True)
  File "/opt/king-phisher/king_phisher/server/database/manager.py", line 258, in init_database
    inspector = sqlalchemy.inspect(engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/inspection.py", line 63, in inspect
    ret = reg(subject)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/reflection.py", line 139, in _insp
    return Inspector.from_engine(bind)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/reflection.py", line 135, in from_engine
    return Inspector(bind)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/reflection.py", line 109, in __init__
    bind.connect().close()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2082, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2168, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2142, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1292, in _do_get
    return self.connection
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 754, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1264, in connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 392, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) unable to open database file
.

## Environment Details

KALI 2016

**Comment by zeroSteiner** [comment]
It's complaining that your database connection is not properly configured in the servers configuration file. It is **highly recommended** that you do not use SQLite like you are and instead use PostgreSQL. Instructions on how to set this up are available in the wiki on the [Database](https://github.com/securestate/king-phisher/wiki/Database) page.

**Comment by zeroSteiner** [comment]
Haven't gotten a response in a week so I'm closing this out.
