### ISSUE TITLE
Ubuntu 14.04 Client Installation Issue

### ISSUE THREAD

**Issue by seanjackson** [securestate/king-phisher#19]
am i using ubuntu 14.0.4 for kingphisher my problem now is that i cannot install the client

**Comment by seanjackson** [comment]
i used the automated script and the i also used downloaded the zip file for kingphisher but it is not working

**Comment by zeroSteiner** [comment]
You need to provide more details as to what exactly is not working. For example, do you get a python stack trace, or does the automated install file not complete successfully? If you do not get a stack trace what error messages are you seeing?

Ubuntu 14.04 is a well supported system for both the client and server. Are you using Ubuntu 14.04 desktop or server edition?

**Comment by seanjackson** [comment]
﻿﻿i want to send u the details when i write python KingPhisher

**Comment by seanjackson** [comment]
edmond@Edmond:~/Desktop/king-phisher-master$ python KingPhisher
Traceback (most recent call last):
  File "KingPhisher", line 43, in <module>
    from king_phisher.client import application
  File "/home/edmond/Desktop/king-phisher-master/king_phisher/client/application
.py", line 41, in <module>
    from king_phisher.client import client
  File "/home/edmond/Desktop/king-phisher-master/king_phisher/client/client.py",
 line 48, in <module>
    from king_phisher.client import tools
  File "/home/edmond/Desktop/king-phisher-master/king_phisher/client/tools.py",
line 42, in <module>
    from king_phisher.client import client_rpc
  File "/home/edmond/Desktop/king-phisher-master/king_phisher/client/client_rpc.
py", line 42, in <module>
    from king_phisher import geoip
  File "/home/edmond/Desktop/king-phisher-master/king_phisher/geoip.py", line 44
, in <module>
    import geoip2.database
  File "/usr/local/lib/python2.7/dist-packages/geoip2/database.py", line 12, in
<module>
    import maxminddb
  File "/usr/local/lib/python2.7/dist-packages/maxminddb/__init__.py", line 4, i
n <module>
    import maxminddb.reader
  File "/usr/local/lib/python2.7/dist-packages/maxminddb/reader.py", line 18, in
 <module>
    from maxminddb.compat import byte_from_int, int_from_byte, ipaddress
  File "/usr/local/lib/python2.7/dist-packages/maxminddb/compat.py", line 6, in
<module>
    import ipaddr as ipaddress  # pylint:disable=F0401
ImportError: No module named ipaddr
edmond@Edmond:~/Desktop/king-phisher-master$

**Comment by seanjackson** [comment]
this what happen 
master$ sudo tools/install.sh
[sudo] password for edmond:
Linux version detected as Ubuntu
Project directory found at /home/edmond/Desktop/king-phisher-master
Installing Ubuntu dependencies
Reading package lists... Done
Building dependency tree      
Reading state information... Done
python-dev is already the newest version.
python-pip is already the newest version.
libfreetype6-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 344 not upgraded.
Reading package lists... Done
Building dependency tree      
Reading state information... Done
gir1.2-vte-2.90 is already the newest version.
python-cairo is already the newest version.
python-paramiko is already the newest version.
libgeos++-dev is already the newest version.
gir1.2-gtk-3.0 is already the newest version.
gir1.2-webkit-3.0 is already the newest version.
libgtk-3-dev is already the newest version.
python-gi is already the newest version.
python-gi-cairo is already the newest version.
python-gobject is already the newest version.
python-gobject-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 344 not upgraded.
Reading package lists... Done
Building dependency tree      
Reading state information... Done
libpq-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 344 not upgraded.
Installing Python package dependencies from pypi
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
Installing the client desktop application file
Updating the GTK icon cache
gtk-update-icon-cache: Cache file created successfully.
Installing the King Phisher upstart service file in /etc/init/
Starting the King Phisher service
king-phisher start/running, process 2882
edmond@Edmond:~/Desktop/king-phisher-master$

**Comment by seanjackson** [comment]
please can you review for me and tell me what is going on i am running the ununti desktop edition

**Comment by zeroSteiner** [comment]
It looks like the part where pip should have installed the packages from the requirements file failed. This is possibly due to a network error judging by the "incomplete read".

From within the King Phisher directory try running the command: ```sudo pip install -r requirements.txt``` which will retry the step which failed. If it fails again, copy and paste the error from the command back in here so I can see if it's the same or something else.

**Comment by seanjackson** [comment]
edmond@Edmond:~/Desktop/king-phisher-master$ sudo pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
edmond@Edmond:~/Desktop/king-phisher-master$

**Comment by seanjackson** [comment]
still have the same problem seems like the pip file cannot install

**Comment by zeroSteiner** [comment]
It looks like something is wrong with the pip installation. Try reinstalling the python-pip package using apt-get.

**Comment by seanjackson** [comment]
where u are to figure out the issue

**Comment by zeroSteiner** [comment]
You need to fix pip. Try following the instructions [here](https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991) then re-running the pip command ```sudo pip install -r requirements.txt```.

I can't confirm this but it looks like running ```sudo easy_install requests==2.2.1``` might fix the problem.

**Comment by seanjackson** [comment]
seems like pip is a serious bug having a hard time fixing this issue

**Comment by zeroSteiner** [comment]
Due to the issue being in pip, and fixing it being out side the scope of the King Phisher project, I'm going to go ahead and close this issue.

After you have resolved the pip issues, you can retry finishing the King Phisher installation.
