### ISSUE TITLE
Unable to start KingPhisherServer

### ISSUE THREAD

**Issue by str4n63r** [securestate/king-phisher#203]
## Issue Description
**I received below error:**
ERROR    failed to bind server to address (socket error #98)
ERROR    socket error #98 (Address already in use)
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/build.py", line 159, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 757, in __init__
    super(KingPhisherServer, self).__init__(handler_klass, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 1694, in __init__
    server = server_klass((address[0], address[1]), handler_klass, config=self.__config)
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 666, in __init__
    super(ServerNonThreaded, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 682, in server_bind
    super(ServerNonThreaded, self).server_bind(*args, **kwargs)
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
CRITICAL server failed to build with error: socket error #98 (Address already in use)
INFO     unloading 0 plugins

## Reproduction Steps
I tried executing below command to start king-phisher server:
**./KingPhisherServer -L INFO -f server_config.yml**

## Environment Details
Host OS:  Kali 2016 R2 32-Bit
King Phisher Version: Latest Version

**Comment by wolfthefallen** [comment]
@str4n63r Please review the FAQ for[ Socket failed to bind issue](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#socket-bind-failure).
This gennerally occurs when you have an instance of `apache` or `ngix` already running on the system, stop and disable these service for the duration that you are utilizing the `KingPhisherServer`.

**Comment by str4n63r** [comment]
Thank you @wolfthefallen. That solved my issue.

**Comment by wolfthefallen** [comment]
@str4n63r No problem, Happy Phishing!
