### ISSUE TITLE
An Error Occurred when opening KingPhisher client

### ISSUE THREAD

**Issue by shifteynz** [securestate/king-phisher#208]
## Issue Description
I get a "An Error Occurred" Message when I...

## Reproduction Steps
1. Start King Phisher Windows client

## Environment Details

Host OS: Ubuntu 16.04.2 LTS
King Phisher Server Version: 1.7.2-beta rev 457e42440603
King Phisher Client Version: 1.7.1 win32

## Error Details / Stack Trace
Error Type: exceptions.KeyError
Error Details: KeyError('mailer.target_field',)
Error UID: a6736362-8ed5-457c-8877-373385fb895c
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.7.1
Platform Version: Windows: 7 6.1.7601 SP1 Multiprocessor Free (Frozen=True)
Python Version: 2.7.12
Gtk Version: 3.14.15
Timezone: Pacific/Auckland

Thread Information:
 => MainThread (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\application.py", line 376, in do_activate
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\windows\main.py", line 250, in __init__
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\tabs\mail.py", line 1037, in __init__
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\tabs\mail.py", line 827, in __init__
KeyError: 'mailer.target_field'

```

**Comment by shifteynz** [comment]
I've removed and reinstalled v1.7.1 client, and rebooted twice. seems to be working ok now. Will close this issue.
