### ISSUE TITLE
"a remote exception occured" when sending mail

### ISSUE THREAD

**Issue by rami418** [securestate/king-phisher#221]
Hi,First than you for that work :)

## Issue Description
I am having an issue when sending a mail (with outlook adress, using Office 365 parameters). Mail is sent "a remote exception occured" and I am not able to view anything like statistics into dashboard.
Mail is received on the other side.
Actually working when no special character is put on the Target Name section.

## Reproduction Steps
1. Start King Phisher server 
- host : 127.0.0.1
- port : a port upper than 1024
- ssl : false
- using Postgresql database
2. Start King Fisher Client
3 New campaign configuration : 
- web server URL : simple login page from templates (reachable)
- source mail : myadress@outlook.fr
- message html : ticket notice from templates (king-phisher-templates/Email_Templates/Credentials/Ticket_Notice/email.html)
- single target with **special character into the Target Name** (I've put "Rémi")

## Environment Details

Host OS: Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux
King Phisher Version: 1.8.0

## Error Details / Stack Trace
-> Client Side

ERROR    an error occurred while sending messages
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/mailer.py", line 523, in run
    emails_done = self._send_messages()
  File "/opt/king-phisher/king_phisher/client/mailer.py", line 742, in _send_messages
    self.rpc('campaign/message/new', campaign_id, target.uid, target.email_address, target.first_name, target.last_name, target.department)
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 515, in __call__
    return self.call(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 573, in call
    raise RPCError('remote method incurred an exception', resp.status, remote_exception=resp_data['exception'])
advancedhttpserver.RPCError: a remote exception occurred 

-> Server Side

ERROR    error: builtins.UnicodeEncodeError occurred while calling rpc method: /campaign/message/new
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 1238, in do_RPC
    response['result'] = rpc_handler(*meth_args, **meth_kwargs)
  File "/opt/king-phisher/king_phisher/server/server_rpc.py", line 103, in wrapper
    result = function(handler_instance, session, *args, **kwargs)
  File "/opt/king-phisher/king_phisher/server/server_rpc.py", line 317, in rpc_campaign_message_new
    session.commit()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 1: ordinal not in range(128)

**Comment by wolfthefallen** [comment]
@rami418 Thank you for the detailed bug report!
I will look into this to see if I can recreate the issue and make a fix.

**Comment by rami418** [comment]
Thank you ! :)

**Comment by wolfthefallen** [comment]
I've been unable to reproduce this issue, where the server side has an error saving a message record with with a special charater `é` in the name. Can you provide any additional details?

**Comment by rami418** [comment]
I was able to reproduce it. So it happen with both single target (with a "é" in the name) and a CSV file.
As shown in the error message, It is using python 3.5.

This is the history of sending (client side, running on windows 7 32bits) : 

Checking the target URL... success, done.
Skipped checking the SPF policy because the SMTP server address could not be detected.
Sending messages started at: jeudi juillet 06, 2017 09:45:00
Message mode is: Email
Connecting to SMTP server... done.
Sending email 1 of 1 with UID: TZsF2qIlRoXlZ5LP to myaddress@plop.com
An error occurred while sending messages.
Disconnected from the SMTP server

The OS which host the client doesn't seems to change anything, got this error with both kali (same machine as the server) and windows 7 32bits.

Tell don't know which details could be useful, you can ask me to launch some commands to debug, i'll help ;)

**Comment by zeroSteiner** [comment]
I was able to track this down. The error is reproducible on a fully patched (as of today July 17, 2017) Kali system and then a fresh clone and install of King Phisher v1.8.

It appears that the issues is the client encoding setting in PostgreSQL as used by Psycopg2 (see this reference to [Unicode with Psycopg2 in the SQLAlchemy docs](http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#unicode-with-psycopg2)).

@rami418 You should be able to fix this yourself by adding `?client_encoding=utf8` to the end of your database connection string in your server configuration file (look for server_config.yml in the king-phisher folder). It should then look something like the following:

```
database: postgresql://king_phisher:SUPERSECRET@localhost/king_phisher?client_encoding=utf8
```

After making that change, just restart your server with `sudo systemctl restart king-phisher`. **Do not share your connection string with us, it has your database password in it.** If you wouldn't mind letting us know if this fixed your issues we'd appreciate it so we can get this closed out. Thanks!

**Comment by rami418** [comment]
Hi,

Issue solved ! ;)
Thanks for your time, have a nice day :)

**Comment by zeroSteiner** [comment]
Added this to the database manager as a parameter to `create_engine`. It will set this configuration now explicitly when used with newer version of libpq. See commit b8a7f638fdcbc5cdc8e3eb556ef4e3bed35930cb for the implementation.
