### ISSUE TITLE
Attempting to clone linkedin login site fails

### ISSUE THREAD

**Issue by cclements** [securestate/king-phisher#231]
Kingphisher rev 6bd8350
Ubuntu 16.04.2 LTS

Attempting to clone linkedin's login page fails with the following error:

```
WARNING  loaded empty on target resource: https://www.linkedin.com/analytics/noauthtracker?type=leo%2EpageTracking&pageType=full_page&pageKey=uas-consumer-login-internal_jsbeacon&trackingInfo=null
WARNING  requested the empty resource with python, but the length appears invalid
WARNING  loaded empty on target resource: https://www.linkedin.com/lite/ua/error?csrfToken=ajax%3A6281124414137269997&_1501023564061
WARNING  failed to request the empty resource with python
WARNING  loaded empty on target resource: https://www.linkedin.com/fizzy/admin?1501023564068
WARNING  requested the empty resource with python, but the length appears invalid
ERROR    error uid: 9281c231-2863-4ed5-8302-13f79f38ebde an unhandled exception was thrown
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/web_cloner.py", line 282, in cb_get_data_finish
    self.copy_resource_data(resource, data)
  File "/opt/king-phisher/king_phisher/client/web_cloner.py", line 170, in copy_resource_data
    if ';' in mime_type:
TypeError: argument of type 'NoneType' is not iterable
WARNING  loaded empty on target resource: https://www.linkedin.com/lite/platformtelemetry
WARNING  requested the empty resource with python, but the length appears invalid
WARNING  loaded empty on target resource: https://www.linkedin.com/lite/rum-track?csrfToken=ajax%3A6281124414137269997
WARNING  requested the empty resource with python, but the length appears invalid
WARNING  loaded empty on target resource: https://www.linkedin.com/lite/platformtelemetry
```

**Comment by wolfthefallen** [comment]
@cclements Thank you for reporting this issue, the fix has been committed into the dev branch with commit 8ab3cd7
