### ISSUE TITLE
Unable to Edit or Preview Email

### ISSUE THREAD

**Issue by routeback** [securestate/king-phisher#248]
## Issue Description
I get a stack trace when I click the Edit or Preview buttons.

## Reproduction Steps
1. Start King Phisher
2. Create a campaign
3. Click on the Edit or Preview buttons

## Environment Details
Host OS: Kali Rolling.
King Phisher Version: 1.9.0-beta4 (rev: fa0ea7c8a6d5)

## Error Details / Stack Trace
```
Error Type: builtins.UnicodeDecodeError
Error Details: UnicodeDecodeError('utf-8', b'\xff\xfe
[...snip]
x00d\x00y\x00>\x00\r\x00\n\x00\r\x00\n\x00<\x00/\x00h\x00t\x00m\x00l\x00>\x00\r\x00\n\x00', 0, 1, 'invalid start byte')
Error UID: 0945fc28-ce36-4458-978f-66eb5973b262
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.9.0-beta4 (rev: fa0ea7c8a6d5)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.3
Gtk Version: 3.22.24
Timezone: America/New_York

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)
    Thread-6 (alive=True daemon=True)
    Thread-7 (alive=True daemon=True)
    Thread-12 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/root/scripts/king-phisher/king_phisher/client/tabs/mail.py", line 1119, in signal_notebook_switch_page
    edit_tab.show_tab()
  File "/root/scripts/king-phisher/king_phisher/client/tabs/mail.py", line 776, in show_tab
    self.load_html_file()
  File "/root/scripts/king-phisher/king_phisher/client/tabs/mail.py", line 625, in load_html_file
    html_data = file_h.read()
  File "/usr/lib/python3.6/codecs.py", line 698, in read
    return self.reader.read(size)
  File "/usr/lib/python3.6/codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by zeroSteiner** [comment]
Looking at the data in the `UnicodeDecodeError` it does not look like it's UTF-8. You'll need to convert and re-encode your message as UTF-8 in order for it to be used with King Phisher.

See [File Encoding](https://github.com/securestate/king-phisher/wiki/Templates#file-encoding) in the wiki. You can use most popular text editors to change the encoding and resave the file.

**Comment by routeback** [comment]
Fantastic, thanks for the reply--this solved my issue.
