### ISSUE TITLE
Cant start KingPhisherServer, Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by sonnh58** [securestate/king-phisher#249]
## Issue Description
I get a stack trace when I start KingFisher server

## Reproduction Steps
1. Start King Phisher

## Environment Details

King Phisher Version: 1.9.0-beta4 (rev: fa0ea7c8a6d5)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.3
Gtk Version: 3.22.24

## Error Details / Stack Trace
```
/root/Downloads/king-phisher/KingPhisherServer -L Debug server_config.yml 
Traceback (most recent call last):
  File "/root/Downloads/king-phisher/KingPhisherServer", line 50, in <module>
    from king_phisher.server import build
  File "/root/Downloads/king-phisher/king_phisher/server/build.py", line 39, in <module>
    from king_phisher.server.server import KingPhisherRequestHandler, KingPhisherServer
  File "/root/Downloads/king-phisher/king_phisher/server/server.py", line 54, in <module>
    from king_phisher.server import server_rpc
  File "/root/Downloads/king-phisher/king_phisher/server/server_rpc.py", line 44, in <module>
    from king_phisher.server import graphql
  File "/root/Downloads/king-phisher/king_phisher/server/graphql.py", line 495, in <module>
    schema = Schema()
  File "/root/Downloads/king-phisher/king_phisher/server/graphql.py", line 480, in __init__
    super(Schema, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/schema.py", line 44, in __init__
    self.build_typemap()
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/schema.py", line 105, in build_typemap
    self._type_map = TypeMap(initial_types, auto_camelcase=self.auto_camelcase, schema=self)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 66, in __init__
    super(TypeMap, self).__init__(types)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/typemap.py", line 16, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 74, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 104, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python3.6/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 236, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 74, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 104, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python3.6/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 236, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 74, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 104, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python3.6/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 236, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 74, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 104, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python3.6/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python3.6/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python3.6/dist-packages/graphene/types/typemap.py", line 236, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python3.6/dist-packages/graphene_sqlalchemy/fields.py", line 27, in type
    "SQLAlchemyConnectionField only accepts SQLAlchemyObjectType types"
AssertionError: SQLAlchemyConnectionField only accepts SQLAlchemyObjectType types
```

when i tried to run service it shown:
```
xim 12 23:53:43 kali systemd[1]: king-phisher.service: Control process exited, code=exited status=1
xim 12 23:53:43 kali systemd[1]: Failed to start King Phisher Server.
xim 12 23:53:43 kali systemd[1]: king-phisher.service: Unit entered failed state.
xim 12 23:53:43 kali systemd[1]: king-phisher.service: Failed with result 'exit-code'.
```

**Comment by zeroSteiner** [comment]
Thanks for  bringing this to our attention. I don't see anything obviously wrong so we'll have to look into it a bit more. Was this a fresh install or an upgraded install, and if it was an upgraded install did you re-update all of the packages with `python3 -m pip install -U -r requirements.txt`?

**Comment by wolfthefallen** [comment]
I have been unable to reproduce this issue. Can you please provide me the output from `python3 -m pip freeze`

**Comment by sonnh58** [comment]
@zeroSteiner @wolfthefallen  i do a fresh install via command : 
```wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && sudo bash ./install.sh
```

At this time, **graphene v2** and **graphene-sqlalchemy v2** was installed and i cant start server service.

When i try to remove **graphene v2** and **graphene-sqlalchemy v2** and install
```
graphene==1.4.1
graphene-sqlalchemy==1.1.1
```
It worked, but after login success, it showed another error


Error Type: king_phisher.errors.KingPhisherGraphQLQueryError
Error Details: KingPhisherGraphQLQueryError()
Error UID: c0929e0b-1636-4cfe-804f-32f7d251f0c2
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.9.0-beta4 (rev: fa0ea7c8a6d5)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.3
Gtk Version: 3.22.24
Timezone: US/Eastern

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-1 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/windows/main.py", line 175, in signal_activate_show_campaign_selection
    self.application.show_campaign_selection()
  File "/opt/king-phisher/king_phisher/client/application.py", line 681, in show_campaign_selection
    dialog = dialogs.CampaignSelectionDialog(self)
  File "/opt/king-phisher/king_phisher/client/dialogs/campaign_selection.py", line 92, in __init__
    self.load_campaigns()
  File "/opt/king-phisher/king_phisher/client/dialogs/campaign_selection.py", line 200, in load_campaigns
    campaigns = self.application.rpc.graphql(campaigns_query)
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 192, in graphql
    query_vars=query_vars
king_phisher.errors.KingPhisherGraphQLQueryError

![image](https://user-images.githubusercontent.com/10656177/32758011-eb21081a-c914-11e7-86ef-f27a9adf6757.png)

**Comment by zeroSteiner** [comment]
Did you restart both the client and server before trying to log in after applying the fix?

**Comment by sonnh58** [comment]
Yes i restarted. I tried to install KingFisher in new virtual machines with
```
graphene==1.4.1
graphene-sqlalchemy==1.1.1
```
Server could start but still have error like that

Error Type: king_phisher.errors.KingPhisherGraphQLQueryError
Error Details: KingPhisherGraphQLQueryError()
Error UID: 25fa2afd-1731-45f5-ada5-5348f9d6ede7
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.9.0-beta4 (rev: 1c1d0aae283d)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.3
Gtk Version: 3.22.24
Timezone: US/Eastern

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/root/Downloads/king-phisher/king_phisher/client/windows/main.py", line 175, in signal_activate_show_campaign_selection
    self.application.show_campaign_selection()
  File "/root/Downloads/king-phisher/king_phisher/client/application.py", line 681, in show_campaign_selection
    dialog = dialogs.CampaignSelectionDialog(self)
  File "/root/Downloads/king-phisher/king_phisher/client/dialogs/campaign_selection.py", line 92, in __init__
    self.load_campaigns()
  File "/root/Downloads/king-phisher/king_phisher/client/dialogs/campaign_selection.py", line 200, in load_campaigns
    campaigns = self.application.rpc.graphql(campaigns_query)
  File "/root/Downloads/king-phisher/king_phisher/client/client_rpc.py", line 192, in graphql
    query_vars=query_vars
king_phisher.errors.KingPhisherGraphQLQueryError

![image](https://user-images.githubusercontent.com/10656177/32766492-c0604cee-c941-11e7-9fdd-d601f606ee5b.png)

**Comment by sonnh58** [comment]
i found solution

add to requirement.txt
```
graphql-core==1.1.0
```
graphql-core v2 causes error

**Comment by zeroSteiner** [comment]
That's a good catch, thanks for letting us know about that @sonnh58. We're going to update our temporary fix until we can get everything fully updated for Graphene v2.

**Comment by zeroSteiner** [comment]
Support for graphene v2 has been added to the `dev` branch in commit c14c5e00d0c23db98172c1cae8ba4c7c56996583.
