### ISSUE TITLE
upgrade kali 2017.3 rolling got me into 'unhandled exceptions' what an irony

### ISSUE THREAD

**Issue by marxenegls** [securestate/king-phisher#250]
# Issue Description
I get a stack trace when I... launch the client

Error Type: builtins.TypeError
Error Details: TypeError("argument of type 'NoneType' is not iterable",)
Error UID: c3ae98e1-df6e-41dd-a404-7c6d34c02998
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.9.0-beta4 (rev: cc43c91ff98e)
Platform Version: Linux: Kali 2017.04 rolling
Python Version: 3.5.4
Gtk Version: 3.22.24

Thread Information:
 => MainThread (alive=True daemon=False)
## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash 
i had previously cleaned up params in ~/.config/king-phisher/config.json 
changed host ip:port, date, sftp params, ssh key type .
but i also had a massive update,i checked for it after filezilla had its own non fatal wxGTK3 exception. ,rebooted and switched server config to Http ,changed to port 81 and removed ssl certs. I had given up on https , after countless tries ,plus self signed certificates wont do anyways, will try certbot eventually.  

## Environment Details

Host OS:Kali 2, 2017.04 rolling (Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux)
King Phisher Version: 1.9.0-beta4

## Error Details / Stack Trac/opt/king-phisher$ ./KingPhisher
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/application.py", line 486, in do_config_load
    self.config = serializers.JSON.load(tmp_file)
  File "/opt/king-phisher/king_phisher/serializers.py", line 114, in load
    return cls.loads(file_h.read(), *args, **kwargs)
  File "/opt/king-phisher/king_phisher/serializers.py", line 154, in loads
    return json.loads(data, object_hook=cls._json_object_hook)
  File "/usr/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 61 column 24 (char 2057)
ERROR    error uid: b3fddb5f-de7c-4491-8c20-5ffe894af185 an unhandled exception was thrown
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/application.py", line 380, in do_activate
    self.main_window = main.MainAppWindow(self.config, self)
  File "/opt/king-phisher/king_phisher/client/windows/main.py", line 251, in __init__
    mailer_tab = MailSenderTab(self, self.application)
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 1059, in __init__
    config_tab = MailSenderConfigurationTab(self.application)
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 835, in __init__
    super(MailSenderConfigurationTab, self).__init__(*args, **kwargs)
  File "/opt/king-phisher/king_phisher/client/gui_utilities.py", line 656, in __init__
    self.objects_load_from_config()
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 856, in objects_load_from_config
    super(MailSenderConfigurationTab, self).objects_load_from_config()
  File "/opt/king-phisher/king_phisher/client/gui_utilities.py", line 733, in objects_load_from_config
    if not gtype in GOBJECT_PROPERTY_MAP or not config_name in self.config:
TypeError: argument of type 'NoneType' is not iterable
--->
```
great project thanks 
```

**Comment by zeroSteiner** [comment]
It looks like your configuration file is corrupt. Try moving it and seeing if that fixes the problem. The configuration file exists under `~/.config/king-phisher/config.json`, just rename it `config.bk.json`.

**Comment by marxenegls** [comment]
fixed edited config.json file
