### ISSUE TITLE
problem sending 

### ISSUE THREAD

**Issue by fdeleon463** [securestate/king-phisher#26]
Hi guys, 

So, i installed the latest version and the first 3 o 4 test went really smooth.

But now when i try to send, i get this:

RPC Error: N/A (Not an RPC error)
King Phisher Version: 0.2.0
Platform Version: Windows: 7 6.1.7601 SP1 Multiprocessor Free (Frozen=True)
Python Version: 2.7.9
Gtk Version: 3.8.9

Traceback (most recent call last):
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 229, in signal_button_clicked_sender_start
  File "Y:\KingPhisher\king_phisher\client\mailer.py", line 547, in missing_files
  File "Y:\KingPhisher\king_phisher\client\mailer.py", line 471, in _prepare_env
  File "Y:\KingPhisher\king_phisher\client\mailer.py", line 96, in format_message
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 841, in from_string
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 540, in compile
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 459, in _parse
  File "C:\Python27\lib\site-packages\jinja2\parser.py", line 32, in __init__
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 490, in _tokenize
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 484, in preprocess
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 181745: ordinal not in range(128)

**Comment by zeroSteiner** [comment]
That error comes from an invalid character in the message template. I need to go back and look at the issue but until I push up a fix you can work around it by finding and deleting the unicode character in the message HTML.

**Comment by fdeleon463** [comment]
Oh, ok great, will do.

Thanks

**Comment by fdeleon463** [comment]
I changed the message html and worked, since i was just testing before starting a real campaign
inside the HTML message i was inserting a landing page link like this:

"http://10.200.40.18/landingpage.html"

Seems like doesnt like it :smile:

**Comment by zeroSteiner** [comment]
Alright I pushed up a fix to properly handle the message html file using UTF-8 encoding. The change is in the development branch and will eventually make it's way into the next Windows build with the final release of 0.2.1.

Thanks for reporting this issue.

**Comment by fdeleon463** [comment]
Hi, im still stuck with inserting the link inside the html message with the 0.2.0 version (windows client)
It just keeps failing, the only way it works is if the message html is plain text.

The linux client has the same issue?

Thanks for the help

**Comment by zeroSteiner** [comment]
If you're still getting the same error then it has to be because there is a non-ascii character in the message template that needs to be removed. Ensure all of the input fields and the message template only contain valid ascii characters.

This linux client has been updated to resolve this issue, the windows client will have to wait until the next build is released.

**Comment by fdeleon463** [comment]
Oh, ok great.
I give the linux client a shot then.

Thanks a lot :+1:
