### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by rageissweet** [securestate/king-phisher#268]
Error Type: advancedhttpserver.RPCError
Error Details: RPCError(message='Unauthorized', status=401, remote_exception=False)
Error UID: cc74113d-3a99-4563-99d8-4ff1dfcda9a6
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.10.0-beta (rev: 6bab024ed811)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.4
Gtk Version: 3.22.28
Timezone: Europe/Berlin

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-1 (alive=True daemon=True)
    Thread-6 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/tabs/campaign.py", line 187, in signal_server_event_db
    row_data = self.format_node_data(get_node(row.id))
  File "/opt/king-phisher/king_phisher/client/tabs/campaign.py", line 180, in <lambda>
    get_node = lambda id: self.rpc.graphql(self.node_query, {'id': str(id)})['db']['node']
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 199, in graphql
    response = self.call('graphql', query, query_vars=query_vars)
  File "/usr/local/lib/python3.6/dist-packages/advancedhttpserver.py", line 601, in call
    raise RPCError(resp.reason, resp.status)
advancedhttpserver.RPCError: the server responded with 401 'Unauthorized'

**Comment by zeroSteiner** [comment]
You need to re-log into the server. This happens sometimes if you restart the server while the client is running.

**Comment by rageissweet** [comment]
hi, thx for fast answer. how re-log into the server ?
sry for my bad english
i had an second errror by start king phisher its
Error Type: builtins.AttributeError
Error Details: AttributeError("'AxesSubplot' object has no attribute 'set_axis_bgcolor'",)
Error UID: 0a60eff9-c008-4175-bbab-3e468bfa59d7
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.10.0-beta (rev: 6bab024ed811)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.4
Gtk Version: 3.22.28
Timezone: Europe/Berlin

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-1 (alive=True daemon=True)
    Thread-2 (alive=True daemon=True)
    Thread-3 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/gui_utilities.py", line 122, in wrapper
    results.append(function(*args, **kwargs))
  File "/opt/king-phisher/king_phisher/client/tabs/campaign.py", line 595, in <lambda>
    info_cache.update(gui_utilities.glib_idle_add_wait(lambda g=graph: g.refresh(info_cache, self.loader_thread_stop)))
  File "/opt/king-phisher/king_phisher/client/graphs.py", line 337, in refresh
    self._load_graph(info_cache)
  File "/opt/king-phisher/king_phisher/client/graphs.py", line 641, in _load_graph
    self.graph_bar(bars, len(yticklabels), yticklabels[:len(bars)])
  File "/opt/king-phisher/king_phisher/client/graphs.py", line 505, in graph_bar
    bar_container = self._barh(ax1, bars, height, max_bars)
  File "/opt/king-phisher/king_phisher/client/graphs.py", line 460, in _barh
    ax.set_axis_bgcolor(color_bg)
AttributeError: 'AxesSubplot' object has no attribute 'set_axis_bgcolor'

**Comment by rageissweet** [comment]
sry for nerdy quests
