### ISSUE TITLE
FATAL: password authentication failed for user "king_phisher"  ???

### ISSUE THREAD

**Issue by chrisandjer949** [securestate/king-phisher#281]
## Issue Description
I get a stack trace when I...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```
king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Wed 2018-03-28 19:48:21 PDT; 54s ago
  Process: 3116 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_conf

Mar 28 19:46:53 kali2 python3[3116]:   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/defaul
Mar 28 19:46:53 kali2 python3[3116]:     return self.dbapi.connect(*cargs, **cparams)
Mar 28 19:46:53 kali2 python3[3116]:   File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130,
Mar 28 19:46:53 kali2 python3[3116]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasy
Mar 28 19:46:53 kali2 python3[3116]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  pa
Mar 28 19:46:53 kali2 python3[3116]: FATAL:  password authentication failed for user "king_phisher"
Mar 28 19:46:53 kali2 python3[3116]:  (Background on this error at: http://sqlalche.me/e/e3q8)
Mar 28 19:48:21 kali2 systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Mar 28 19:48:21 kali2 systemd[1]: king-phisher.service: Failed with result 'timeout'.
Mar 28 19:48:21 kali2 systemd[1]: Failed to start King Phisher Server.

====================================================

root@kali2:/opt/king-phisher# sudo ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.10.0 (rev: 63aaf4772ed9) python version: 3.6.5
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql-setup was not found
DEBUG    postgresql service is already running via systemctl
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 345, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 784, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1189, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1186, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "king_phisher"
FATAL:  password authentication failed for user "king_phisher"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./KingPhisherServer", line 243, in <module>
    sys.exit(main())
  File "./KingPhisherServer", line 237, in main
    status_code = build_and_run(arguments, config, plugin_manager, log_file)
  File "./KingPhisherServer", line 71, in build_and_run
    king_phisher_server = build.server_from_config(config, plugin_manager=plugin_manager)
  File "/opt/king-phisher/king_phisher/server/build.py", line 145, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 875, in __init__
    self.database_engine = db_manager.init_database(config.get('server.database'), extra_init=True)
  File "/opt/king-phisher/king_phisher/server/database/manager.py", line 336, in init_database
    inspector = sqlalchemy.inspect(engine)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/inspection.py", line 63, in inspect
    ret = reg(subject)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/reflection.py", line 139, in _insp
    return Inspector.from_engine(bind)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/reflection.py", line 134, in from_engine
    return bind.dialect.inspector(bind)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/base.py", line 2001, in __init__
    reflection.Inspector.__init__(self, conn)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/reflection.py", line 109, in __init__
    bind.connect().close()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 345, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 784, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1189, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1186, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "king_phisher"
FATAL:  password authentication failed for user "king_phisher"
 (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by zeroSteiner** [comment]
You need to reset your postgresql password. This is covered in the FAQ.

**Comment by chrisandjer949** [comment]
Ok, finally figured out how to reset the postgresql password for king_phisher account.  Rather painful for me as a first time user.  Thank you!

**Comment by zeroSteiner** [comment]
I guess the error is a bit cryptic. Commit a8cc7b1225f319743d69ef54b17fa44dfb975d91 tries to make it a little more clear.

**Comment by Allen-Paul** [comment]
I've similar issue and I did try resetting the postgresql password as mentioned in the FAQ, but it does not seem to fix the issue.
#
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "king_phisher"
FATAL:  password authentication failed for user "king_phisher"

(Background on this error at: http://sqlalche.me/e/e3q8)
CRITICAL server failed to build with error: database initialization failed
#
do I need to add/edit this new password in some config file?
