### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/basemap/data/epsg'

### ISSUE THREAD

**Issue by chrisandjer949** [securestate/king-phisher#283]
## Issue Description
I get a stack trace when I...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```
root@kali2:/opt/king-phisher# ./KingPhisher
Traceback (most recent call last):
  File "./KingPhisher", line 49, in <module>
    from king_phisher.client import application
  File "/opt/king-phisher/king_phisher/client/application.py", line 55, in <module>
    from king_phisher.client import dialogs
  File "/opt/king-phisher/king_phisher/client/dialogs/__init__.py", line 37, in <module>
    from .configuration import *
  File "/opt/king-phisher/king_phisher/client/dialogs/configuration.py", line 39, in <module>
    from king_phisher.client import graphs
  File "/opt/king-phisher/king_phisher/client/graphs.py", line 70, in <module>
    import mpl_toolkits.basemap
  File "/usr/lib/python3/dist-packages/mpl_toolkits/basemap/__init__.py", line 141, in <module>
    epsgf = open(os.path.join(basemap_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/basemap/data/epsg'

**Comment by wolfthefallen** [comment]
It appears basemaps was not correctly installed. 
I know with kali basemap is generally installed and managed with `apt`. 
There is a couple of options you can use to attempt to resolve this issue
1)  first make sure you are up-to-date `sudo apt update && sudo apt upgrade`
2) Make sure you are on that latest version of [kali ](https://www.kali.org/downloads/) 
  a) after setup the new version of kali install king-phisher  `sudo apt install king-phisher`
3) Manually manage the package through pip. `sudo python3 -m pip uninstall basemap && sudo python3 -m pip install https://github.com/matplotlib/basemap/archive/v1.1.0.tar.gz`

**Comment by ghltshubh** [comment]
doesn't work now.

**Comment by zeroSteiner** [comment]
@ghltshubh Yeah, we've since up dated that's no longer the package that needs to be installed. The latest is defined in the Pipfile.
