### ISSUE TITLE
King-Phisher freezes

### ISSUE THREAD

**Issue by polux1** [securestate/king-phisher#338]
## Issue Description

After the latest update (Kali 2019.1), the app freezes when trying to login.
There's an error window, but I can;t see what is says because the login window is on top.

## Reproduction Steps
sudo ./KingPhisherServer -L DEBUG server_config.yml

## Environment Details

Host OS: Kali 2019.1
King Phisher Version: KingPhisher Version: 1.12.0 (rev: a311f02f3e39)

## Error Details / Stack Trace

```
sudo ./KingPhisherServer -L DEBUG server_config.yml
[sudo] password for polux: 
DEBUG    target diretory: /opt/king-phisher
INFO     checking for the pipenv environment
DEBUG    pipenv path: '/usr/local/bin/pipenv'
DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile
Loading .env environment variables…
DEBUG    king phisher version: 1.12.0 (rev: a311f02f3e39) python version: 3.6.7
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql-setup was not found
DEBUG    postgresql service is already running via systemctl
polux@kali /o/king-phisher> DEBUG    current database schema version: 8 (latest)
DEBUG    connected to postgresql database: king_phisher
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
DEBUG    use pam service 'sshd' for authentication
DEBUG    forked an authenticating process with pid: 2323
INFO     the job manager has been started
INFO     adding new job with id: e2960611-870a-40db-b974-995b705f70b1 and callback function: _maintenance
INFO     adding new job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    web socket manager worker running in tid: 0x7f55e6335700
WARNING  the specified geoip database is empty, downloading a new copy
DEBUG    Starting new HTTP connection (1): geolite.maxmind.com
Traceback (most recent call last):
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f55e633eb00>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='geolite.maxmind.com', port=80): Max retries exceeded with url: /download/geoip/database/GeoLite2-City.mmdb.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55e633eb00>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/build.py", line 145, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 913, in __init__
    self.__geoip_db = geoip.init_database(config.get('server.geoip.database'))
  File "/opt/king-phisher/king_phisher/geoip.py", line 102, in init_database
    download_geolite2_city_db(database_file)
  File "/opt/king-phisher/king_phisher/geoip.py", line 72, in download_geolite2_city_db
    response = requests.get(DB_DOWNLOAD_URL, stream=True)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/king-phisher/.venv/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='geolite.maxmind.com', port=80): Max retries exceeded with url: /download/geoip/database/GeoLite2-City.mmdb.gz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55e633eb00>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/king-phisher/king_phisher/server/__main__.py", line 242, in <module>
    sys.exit(main())
  File "/opt/king-phisher/king_phisher/server/__main__.py", line 236, in main
    status_code = build_and_run(arguments, config, plugin_manager, log_file)
  File "/opt/king-phisher/king_phisher/server/__main__.py", line 70, in build_and_run
    king_phisher_server = build.server_from_config(config, plugin_manager=plugin_manager)
  File "/opt/king-phisher/king_phisher/server/build.py", line 147, in server_from_config
    error_number, error_message = error.args
ValueError: not enough values to unpack (expected 2, got 1)
DEBUG    executing job with id: e2960611-870a-40db-b974-995b705f70b1 and callback function: _maintenance
DEBUG    running periodic maintenance tasks
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
polux@kali /o/king-phisher> DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
DEBUG    executing job with id: 3f106a8d-8fb7-40aa-bc7b-042a258db1b0 and callback function: ping_all
```

```
./KingPhisher -L DEBUG
DEBUG    target diretory: /opt/king-phisher
INFO     checking for the pipenv environment
DEBUG    pipenv path: '/usr/local/bin/pipenv'
DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile
Loading .env environment variables…
DEBUG    king phisher version: 1.12.0 (rev: a311f02f3e39) python version: 3.6.7
DEBUG    client running in process: 3503 main tid: 0x7f3d6a011740
DEBUG    using ui data from glade file: /opt/king-phisher/data/client/king_phisher/king-phisher-client.ui
DEBUG    gi.repository GLib version: 2.58.1
DEBUG    gi.repository GObject version: 3.28.3
DEBUG    gi.repository Gtk version: 3.24.1
DEBUG    gi.repository VTE version: 2.91
DEBUG    matplotlib version: 2.2.2
INFO     loading the config from: /home/polux/.config/king-phisher/config.json
INFO     loading 1 plugins
DEBUG    plugin 'check_for_updates' has been loaded
DEBUG    client loaded in 0.00 seconds
DEBUG    resetting the gtk-theme-name property to it's default value
DEBUG    resetting the gtk-icon-theme-name property to it's default value
DEBUG    loading style from css file: /opt/king-phisher/data/client/king_phisher/style/theme.v2.css
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_file_open
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_file_quit
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_rpc_terminal
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_sftp_client
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_create_graph
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.button_target_file_select
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.calendar_calendar_invite_date
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_calendar_invite_all_day
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_calendar_request_rsvp
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_message_uid_charset_digits
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_message_uid_charset_lower
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_message_uid_charset_upper
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.combobox_importance
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.combobox_sensitivity
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_webserver_url
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_calendar_invite_location
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_calendar_invite_summary
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_company_name
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_recipient_email_cc
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_recipient_email_to
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email_smtp
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email_alias
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_subject
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_reply_to_email
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_html_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_name
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_email_address
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_attachment_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.expander_calendar_invite_settings
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.expander_email_settings
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.label_target_count
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_message_type_calendar_invite
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_message_type_email
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_bcc
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_cc
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_to
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_type_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_type_single
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_duration
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_start_hour
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_start_minute
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.viewport
DEBUG    loading GTK builder object with id: MailSenderEditTab.toolbutton_save_as_html_file
DEBUG    loading GTK builder object with id: MailSenderEditTab.toolbutton_save_html_file
DEBUG    loading GTK builder object with id: MailSenderEditTab.view_html_file
DEBUG    loading HTML completion data from: /opt/king-phisher/data/client/king_phisher/completion/html.json
DEBUG    loading Jinja completion data from: /opt/king-phisher/data/client/king_phisher/completion/jinja.json
DEBUG    loading GTK builder object with id: MailSenderSendTab.button_mail_sender_start
DEBUG    loading GTK builder object with id: MailSenderSendTab.button_mail_sender_stop
DEBUG    loading GTK builder object with id: MailSenderSendTab.textview_mail_sender_progress
DEBUG    loading GTK builder object with id: MailSenderSendTab.togglebutton_mail_sender_pause
DEBUG    loading GTK builder object with id: MailSenderSendTab.progressbar_mail_sender
DEBUG    loading GTK builder object with id: MailSenderSendTab.scrolledwindow_mail_sender_progress
INFO     matplotlib is installed, dashboard will be available
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_top_left
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_top_right
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_bottom
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_top_left
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_top_right
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_bottom
WARNING  /opt/king-phisher/.venv/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

DEBUG    dashboard refresh frequency set to 300 seconds
DEBUG    loading GTK builder object with id: CampaignViewMessagesTab.button_refresh
DEBUG    loading GTK builder object with id: CampaignViewMessagesTab.treeview_campaign
DEBUG    loading GTK builder object with id: CampaignViewVisitsTab.button_refresh
DEBUG    loading GTK builder object with id: CampaignViewVisitsTab.treeview_campaign
DEBUG    loading GTK builder object with id: CampaignViewCredentialsTab.button_refresh
DEBUG    loading GTK builder object with id: CampaignViewCredentialsTab.treeview_campaign
DEBUG    loading GTK builder object with id: LoginDialog.button_connect
DEBUG    loading GTK builder object with id: LoginDialog.entry_server
DEBUG    loading GTK builder object with id: LoginDialog.entry_server_username
DEBUG    loading GTK builder object with id: LoginDialog.entry_server_password
DEBUG    loading GTK builder object with id: LoginDialog.entry_server_one_time_password
DEBUG    loading GTK builder object with id: LoginDialog.label_main
DEBUG    loading GTK builder object with id: LoginDialog.label_server_one_time_password
DEBUG    loading GTK builder object with id: LoginDialog.revealer_server_one_time_password
DEBUG    loading GTK builder object with id: LoginDialog.spinbutton_server_remote_port
DEBUG    loading GTK builder object with id: LoginDialog.switch_server_use_ssl
INFO     connecting to local king phisher instance
DEBUG    using serializer: application/json
DEBUG    using serializer: binary/message-pack
DEBUG    calling RPC method: version
```

**Comment by zeroSteiner** [comment]
Looks like the server is having issues downloading the maxmind database. It should fail gracefully but apparently it's not.

So you can try two things to get the database file:
1. Download it using the `--update-geoip-db` flag like `# ./KingPhisherServer -L DEBUG -f --update-geoip-db ./server_config.yml`.
    * If it finishes successfully, it should exit out gracefully and then you can start the server normally
1. Download the database file manually and place it where it says it needs to be in the `server_config.yml` file under the `geoip.database` setting. This is generally `/var/king-phisher/geoip.mmdb`.
    * The URL is http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz, make sure you decompress the database though, the whole command should be something like `curl http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz | gunzip >> geoip.mmdb`

**Comment by polux1** [comment]
That was it! It failed to download the geoip DB because cloudflare was blocking the request.
Downloaded and extracted it to /var/king-phisher and it's working now.
Thank you!

**Comment by zeroSteiner** [comment]
Cool, I just pushed up commit 998b5d3c048f77fbd2150a8646e322d09405a660 to address this. I'm classifying it as a bug since the error message should be more meaningful. Unfortunately we can't really start the server without this data file, but at least now it should be more obvious as to what the issue is.
