### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by klint-k** [securestate/king-phisher#348]
## Issue Description
I experience an issue when I... and the results I expected are...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 18.04 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```
 /usr/share/king-phisher/KingPhisher
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/king-phisher/king_phisher/client/__main__.py", line 48, in <module>
    from king_phisher.client import application
  File "/usr/share/king-phisher/king_phisher/client/application.py", line 51, in <module>
    from king_phisher import ssh_forward
  File "/usr/share/king-phisher/king_phisher/ssh_forward.py", line 46, in <module>
    import paramiko
  File "/usr/lib/python3/dist-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/lib/python3/dist-packages/paramiko/auth_handler.py", line 72, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/lib/python3/dist-packages/paramiko/ssh_gss.py", line 55, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: module 'gssapi' has no attribute 'GSSException'

**Comment by zeroSteiner** [comment]
Please completely fill out the issue template. We need all of the details that it requests to better identify the issue and provide the help that you are requesting. Please do not open a new issue but instead just edit this one and fill out all of the details.

**Comment by klint-k** [comment]
simply put is I start it and it crashes.
I an using kali KDE.
as you see it crashes to soon to see the version number.

**Comment by True-Demon** [comment]
You still didn't fill out the template but it looks like you're missing dependencies related to gssapi. 

Make sure you followed the installation instructions correctly and the install.sh script ran completely. If this doesn't solve the problem, run `pip3 install gssapi` and try it again. Report any new stacktraces it throws, as you may still be missing dependencies.
