### ISSUE TITLE
http status: 501

### ISSUE THREAD

**Issue by BlAd373** [securestate/king-phisher#358]
After i upgrade my distro no any more work 
please some suggestion 
## Issue Description
WARNING  failed to connect to the remote rpc service due to http status: 501

## Reproduction Steps
1. Start King Phisher
2. after try to login 
failed to connect to the remote rpc service due to http status: 501

## Environment Details
Linux 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux
King Phisher Version: last version

## Error Details / Stack Trace
failed to connect to the remote rpc service due to http status: 501
```

2019-02-25 15:47:26,591 KingPhisher.GeoIP                                  WARNING  the specified geoip database does not exist, downloading a new copy
2019-02-26 16:21:00,157 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-26 19:12:40,319 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-26 19:59:55,882 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-27 18:05:04,910 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-28 10:56:56,235 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-28 11:21:05,272 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-28 14:41:34,655 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-28 14:59:16,231 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-28 17:14:27,348 KingPhisher.Server                                 WARNING  processing shutdown request
2019-02-28 23:41:15,081 KingPhisher.Server                                 WARNING  processing shutdown request
2019-03-01 09:00:37,849 KingPhisher.Server                                 WARNING  processing shutdown request
2019-03-01 09:32:56,876 KingPhisher.Server                                 WARNING  processing shutdown request
2019-03-01 20:12:49,385 KingPhisher.Server                                 WARNING  processing shutdown request
2019-03-02 18:03:55,734 KingPhisher.Server                                 WARNING  processing shutdown request
2019-03-05 16:38:01,161 KingPhisher.Server                                 WARNING  processing shutdown request
2019-03-06 01:15:02,250 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-06 08:12:16,631 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-07 01:31:30,859 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-07 08:46:43,845 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-07 09:03:56,140 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-07 11:07:37,452 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-07 15:55:00,185 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-08 03:27:01,004 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-09 08:52:54,710 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-10 12:59:19,839 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-11 05:48:18,921 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-12 10:26:49,729 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-14 09:07:39,306 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: database initialization failed
2019-03-15 11:25:54,506 KingPhisher.Server.build                           ERROR    failed to bind server to address (socket error #98)
2019-03-15 11:25:54,507 KingPhisher.Server.build                           ERROR    socket error #98 (Address already in use)
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/build.py", line 145, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 870, in __init__
    super(KingPhisherServer, self).__init__(handler_klass, *args, **kwargs)
  File "/opt/king-phisher/.venv/lib/python3.7/site-packages/advancedhttpserver.py", line 1791, in __init__
    server = server_klass((address[0], address[1]), handler_klass, config=self.__config)
  File "/opt/king-phisher/.venv/lib/python3.7/site-packages/advancedhttpserver.py", line 713, in __init__
    super(ServerNonThreaded, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/opt/king-phisher/.venv/lib/python3.7/site-packages/advancedhttpserver.py", line 782, in server_bind
    super(ServerNonThreaded, self).server_bind(*args, **kwargs)
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
2019-03-15 11:25:54,605 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: socket error #98 (Address already in use)
2019-03-15 14:28:56,289 KingPhisher.Server.build                           ERROR    failed to bind server to address (socket error #98)
2019-03-15 14:28:56,290 KingPhisher.Server.build                           ERROR    socket error #98 (Address already in use)
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/server/build.py", line 145, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/usr/share/king-phisher/king_phisher/server/server.py", line 858, in __init__
    super(KingPhisherServer, self).__init__(handler_klass, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/advancedhttpserver.py", line 1780, in __init__
    server = server_klass((address[0], address[1]), handler_klass, config=self.__config)
  File "/usr/lib/python3/dist-packages/advancedhttpserver.py", line 703, in __init__
    super(ServerNonThreaded, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3/dist-packages/advancedhttpserver.py", line 771, in server_bind
    super(ServerNonThreaded, self).server_bind(*args, **kwargs)
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
2019-03-15 14:28:56,295 KingPhisher.Server.CLI                             CRITICAL server failed to build with error: socket error #98 (Address already in use)

**Comment by zeroSteiner** [comment]
Looks like two issues

1. It can't connect to the database, so make sure the PostgreSQL service is running
1. It can't bind to the address, probably because you having something that's already there like apache or whatever so kill that

**Comment by BlAd373** [comment]
thank you i fixed 
postgres issue

**Comment by zeroSteiner** [comment]
If you fixed the postgres issue, does this ticket need to stay open or can I close it?

**Comment by BlAd373** [comment]
Yes sure thanks
