### ISSUE TITLE
Error when creating the first campaign for the first time

### ISSUE THREAD

**Issue by sbrun** [securestate/king-phisher#365]
## Issue Description
When I open king-phisher for the first time, I create the first campaign. The error occurs when I click on "Apply" (to confirm Configuration).

## Reproduction Steps
1. Start King Phisher (very first time)
2. Create a new campaign (the first one)
3. Click on "Apply" to create the new King Phisher campaign

A first error message is shown and if I try to "Apply" again a second error message is shown.

I don't have the errors message when I create a second campaign. 

## Environment Details
Host OS: Kali-rolling
King Phisher Version: 1.13.1 (installed with install.sh)

I first found the issue when I updated the package for Kali. I tested the version 1.13.0-0kali1 (not in kali-rolling for the moment)

## Error Details / Stack Trace
First error message:
```
Error Type: builtins.KeyError
Error Details: KeyError('campaign_id')
Error UID: 40c67547-abe4-4383-9017-78eeed0eb9f3
RPC Error: N/A (Not an RPC error)
King Phisher Version: 1.13.1 (rev: 5dd5c1640a27)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.7.3
Gtk Version: 3.24.5
Timezone: Europe/Paris

Thread Information:
===================
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)

Stack Trace:
============
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/assistants/campaign.py", line 557, in signal_assistant_apply
    old_cid = self.config['campaign_id']
KeyError: 'campaign_id'
```

Second error message:
```
Error Type: advancedhttpserver.RPCError
Error Details: RPCError(message='remote method incurred an exception', status=200, remote_exception=True)
Error UID: 32d59584-301e-414f-854d-21ac480cd71b
RPC Error: Name: builtins.ValueError
King Phisher Version: 1.13.1 (rev: 5dd5c1640a27)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.7.3
Gtk Version: 3.24.5
Timezone: Europe/Paris

Thread Information:
===================
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)

Stack Trace:
============
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/assistants/campaign.py", line 535, in signal_assistant_apply
    raise error
  File "/opt/king-phisher/king_phisher/client/assistants/campaign.py", line 529, in signal_assistant_apply
    cid = self.application.rpc('campaign/new', campaign_name, description=campaign_description)
  File "/opt/king-phisher/.venv/lib/python3.7/site-packages/advancedhttpserver.py", line 560, in __call__
    return self.call(*args, **kwargs)
  File "/opt/king-phisher/.venv/lib/python3.7/site-packages/advancedhttpserver.py", line 618, in call
    raise RPCError('remote method incurred an exception', resp.status, remote_exception=resp_data['exception'])
advancedhttpserver.RPCError: a remote exception occurred
```

**Comment by zeroSteiner** [comment]
I was able to reproduce this issue and fixed it in commit b9922082706cb75e0223792ceb54098377d4a199. Thank you for reporting it to us.
