### ISSUE TITLE
King Phisher Error on New Compaign

### ISSUE THREAD

**Issue by hackgod512** [securestate/king-phisher#369]
Error Type: king_phisher.errors.KingPhisherGraphQLQueryError
Error Details: KingPhisherGraphQLQueryError()
Error UID: b394ffc6-9d74-4fce-abad-c6dd7548e1bd
RPC Error: N/A (Not an RPC error)
King Phisher Version: 1.13.1
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.7.2
Gtk Version: 3.24.5
Timezone: Asia/Kolkata

Thread Information:
===================
 => MainThread (alive=True daemon=False)
    Thread-1 (alive=True daemon=True)

Stack Trace:
============
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/dialogs/campaign_selection.py", line 243, in signal_button_clicked
    assistant = CampaignAssistant(self.application)
  File "/usr/share/king-phisher/king_phisher/client/assistants/campaign.py", line 190, in __init__
    self._load_url_treeview_tsafe(refresh=True)
  File "/usr/share/king-phisher/king_phisher/client/assistants/campaign.py", line 260, in _load_url_treeview_tsafe
    self._url_information['data'] = self.application.rpc.graphql_find_file('get_site_templates.graphql')
  File "/usr/share/king-phisher/king_phisher/client/client_rpc.py", line 241, in graphql_find_file
    return self.graphql_file(path, query_vars=query_vars)
  File "/usr/share/king-phisher/king_phisher/client/client_rpc.py", line 224, in graphql_file
    return self.graphql(query, query_vars=query_vars)
  File "/usr/share/king-phisher/king_phisher/client/client_rpc.py", line 205, in graphql
    query_vars=query_vars
king_phisher.errors.KingPhisherGraphQLQueryError

GraphQL Exception Information:
=============================

GraphQL Errors:
---------------
__init__() got an unexpected keyword argument 'follow_links'

GraphQL Query:
--------------
# retrieve information for all site templates
query getSiteTemplates {
  siteTemplates {
    edges {
      node {
        created
        hostname
        path
        metadata {
          authors
          classifiers
          description
          pages
        }
      }
    }
  }
}

**Comment by zeroSteiner** [comment]
I can't reproduce this. You need provide steps as to what you were doing. Creating a campaign I guess, but was it the first campaign on either the server or that the client has connected to? The later would be in the case of a fresh install of the client.

Also what version of the server are you running? The issue template would have prompted you for this information.
