### ISSUE TITLE
Upgrading from 0.3.0 to 1.0.0 fails on database schema

### ISSUE THREAD

**Issue by pahtzo** [securestate/king-phisher#43]
Previous working install of king-phisher 0.3.0 on Kali 2.0 backed with postgresql.  steps taken:
stopped king-phisher service.
copied /opt/king-phisher dir for backup.
rm -rf /opt/king-phisher
gunzipped king-phisher-1.0.0.tar.gz to /opt/king-phisher
ran tools/install.sh
service fails to start, adjusted server_config.yml to change to existing postgresql database.

started manually with: /opt/king-phisher# /opt/king-phisher/KingPhisherServer -L DEBUG /opt/king-phisher/server_config.yml

Output:
DEBUG    king phisher version: 1.0.0 python version: 2.7.9
INFO     listening on 0.0.0.0:80
INFO     0.0.0.0:80 - serving files has been enabled
INFO     initializing database connection with driver sqlite
DEBUG    current database schema version: 4 (not current)
WARNING  automatically updating the database schema to version 6
INFO     Context impl SQLiteImpl.
INFO     Will assume non-transactional DDL.
INFO     Running upgrade  -> 24a4a626ff7c, Schema v3
CRITICAL database schema upgrade failed with exception: sqlalchemy.exc.OperationalError (pysqlite2.dbapi2.OperationalError) table campaign_types already exists
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/database/manager.py", line 185, in init_database
    alembic.command.upgrade(config, 'head')
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/opt/king-phisher/data/server/king_phisher/alembic/env.py", line 99, in <module>
    run_migrations_online()
  File "/opt/king-phisher/data/server/king_phisher/alembic/env.py", line 92, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/opt/king-phisher/data/server/king_phisher/alembic/versions/24a4a626ff7c_schema_v3.py", line 26, in upgrade
    sqlalchemy.Column('description', sqlalchemy.String)
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/ops.py", line 1098, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 194, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) table campaign_types already exists [SQL: u'\nCREATE TABLE campaign_types (\n\tid INTEGER NOT NULL, \n\tname VARCHAR NOT NULL, \n\tdescription VARCHAR, \n\tPRIMARY KEY (id)\n)\n\n']
CRITICAL failed to upgrade to the latest database schema

Thanks

**Comment by zeroSteiner** [comment]
It looks from the stack trace like SQLite is being used as the database
backend instead of Postgres, is that correct?

**Comment by pahtzo** [comment]
it does look that way but it shouldn't, my config has sqlite commented out and Postgres enabled.

**Comment by zeroSteiner** [comment]
It's definitely trying to use sqlite, you can check if the default database file exists at `/var/king-phisher/king-phisher.db`. I would recommend double checking the configuration file to ensure that postgresql is being used. It's probably trying to use the old sqlite that was initialized the first time King Phisher was installed.

**Comment by pahtzo** [comment]
OK, yes the config was set to sqlite, I probably forgot to reconfigure
it after numerous attempts to upgrade.  Now configured with postgresql
and I also removed the default /var/king-phisher/king-phisher.db file. 
still same error, I suppose at this point I could just drop the database
and create a new one but I'm concerned with losing future campaign data
during upgrades.

/opt/king-phisher/KingPhisherServer -L DEBUG
/opt/king-phisher/server_config.yml
DEBUG    king phisher version: 1.0.0 python version: 2.7.9
INFO     listening on 0.0.0.0:80
INFO     0.0.0.0:80 - serving files has been enabled
INFO     initializing database connection with driver postgresql
root@kali:/opt/king-phisher# DEBUG    current database schema version: 4
(not current)
WARNING  automatically updating the database schema to version 6
INFO     Context impl PostgresqlImpl.
INFO     Will assume transactional DDL.
INFO     Running upgrade  -> 24a4a626ff7c, Schema v3
CRITICAL database schema upgrade failed with exception:
sqlalchemy.exc.ProgrammingError (psycopg2.ProgrammingError) relation
"campaign_types" already exists
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/database/manager.py", line
185, in init_database
    alembic.command.upgrade(config, 'head')
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line
174, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py",
line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py",
line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py",
line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/opt/king-phisher/data/server/king_phisher/alembic/env.py", line
99, in <module>
    run_migrations_online()
  File "/opt/king-phisher/data/server/king_phisher/alembic/env.py", line
92, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File
"/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py",
line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File
"/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py",
line 312, in run_migrations
    step.migration_fn(**kw)
  File
"/opt/king-phisher/data/server/king_phisher/alembic/versions/24a4a626ff7c_schema_v3.py",
line 26, in upgrade
    sqlalchemy.Column('description', sqlalchemy.String)
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File
"/usr/local/lib/python2.7/dist-packages/alembic/operations/ops.py", line
1098, in create_table
    return operations.invoke(op)
  File
"/usr/local/lib/python2.7/dist-packages/alembic/operations/base.py",
line 318, in invoke
    return fn(self, operation)
  File
"/usr/local/lib/python2.7/dist-packages/alembic/operations/toimpl.py",
line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py",
line 194, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py",
line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File
"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line
914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py",
line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File
"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line
968, in _execute_ddl
    compiled
  File
"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line
1146, in _execute_context
    context)
  File
"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line
1341, in _handle_dbapi_exception
    exc_info
  File
"/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line
199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File
"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line
1139, in _execute_context
    context)
  File
"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py",
line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) relation "campaign_types"
already exists
 [SQL: '\nCREATE TABLE campaign_types (\n\tid SERIAL NOT NULL, \n\tname
VARCHAR NOT NULL, \n\tdescription VARCHAR, \n\tPRIMARY KEY (id)\n)\n\n']
CRITICAL failed to upgrade to the latest database schema

**Comment by zeroSteiner** [comment]
Recreating the database would certainly be the quickest and easiest way to remedy the situation. It looks like the `campaign_types` table already exists which might have come from a previously interrupted upgrade attempt. Creating that table is the first operation in the upgrade script, you could try removing the campaign_types, company_departments, industries, and companies tables and see if the upgrade will complete.

**Comment by pahtzo** [comment]
Tried those, no dice.  I just dropped the whole db and created a new one from scratch.  Working fine now.  Thanks for your help on this.

**Comment by zeroSteiner** [comment]
Since it's working fine now, I'm going to close this issue. If you have any more trouble just open another.
