### ISSUE TITLE
Clone page error

### ISSUE THREAD

**Issue by Hemza** [securestate/king-phisher#85]
## Issue Description
I get an error when i've tried to clone an OWA (exchange server 2003) loginpage

## Reproduction Steps
1. Start King Phisher
2. Tools-> clone web page --> target URL

## Error Details / Stack Trace
```
Error Type: exceptions.UnicodeDecodeError
Error Details: UnicodeDecodeError('utf8', '\r\n<!-- {57A118C6-2DA9-419d-BE9A-F92B0F9A418B} -->\r\n<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">\r\n<!--Copyright (c) 2000-2003 Microsoft Corporation.  All rights reserved.-->\r\n<HTML ><HEAD>\r\n\t\t<META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=iso-8859-1">\r\n\t\t<META HTTP-EQUIV="Pragma" CONTENT="no-cache">\r\n\t\t<META HTTP-EQUIV="Expires" CONTENT="0">\r\n\t\t<TITLE>Microsoft Outlook Web Access</TITLE>\r\n\t\t<STYLE>\r\n\t\t\tBODY {font-size:70%;}\r\n\t\t\tTABLE {font-size:100%}\r\n\r\n\t\t\tSELECT, INPUT, TEXTAREA, BUTTON, LABEL, BODY\r\n\t\t\t{\r\n\t\t\t\tfont-family:Tahoma,Arial,Helvetica,Sans-serif;\r\n\t\t\t}\r\n\t\t\ta:link\t\t{ color: #3D5FA3; text-decoration: none }\r\n\t\t\ta:visited\t{ color: #3D5FA3; text-decoration: none }\r\n\t\t\ta:hover\t\t{ text-decoration: underline }\r\n\t\t\t.sideBar\r\n\t\t\t{\r\n\t\t\t\tbackground-image: url(/exchweb/img/logon_IE_bot.gif);\r\n\t\t\t\tbackground-repeat: repeat-y;\r\n\t\t\t\tvertical-align:left;\r\n\t\t\t\theight:100%;\r\n\t\t\t}\r\n\t\t\t.logoTD \r\n\t\t\t{\r\n\t\t\t\tBORDER-TOP-WIDTH: 1px;\r\n\t\t\t\tBORDER-LEFT-WIDTH: 1px;\r\n\t\t\t\tPADDING-BOTTOM: 5px;\r\n\t\t\t\tBORDER-BOTTOM: #ecbe3e 1px solid;\r\n\t\t\t\tBORDER-RIGHT-WIDTH: 1px;\r\n\t\t\t}\r\n\t\t\t.mainTable\r\n\t\t\t{\r\n\t\t\t \tBORDER-RIGHT: #243760 1px solid;\r\n\t\t\t \tBORDER-TOP: #243760 1px solid;\r\n\t\t\t \tBORDER-LEFT: #243760 1px solid;\r\n\t\t\t \tBORDER-BOTTOM: #243760 1px solid;\r\n\t\t\t \tBORDER-COLLAPSE: collapse; \r\n\t\t\t}\r\n\t\t\t.standardTable\r\n\t\t\t{\r\n\t\t\t\tBORDER-COLLAPSE: collapse;\r\n\t\t\t}\r\n\t\t</STYLE> \r\n\r\n\t\t<NOSCRIPT>\r\n\t\t\t<TABLE id="borderTable" dir="LTR" class="standardTable" cellSpacing=0 cellPadding=0 height="100%" width="100%" bgColor="#3D5FA3" border=0>\r\n\t\t\t<TR>\r\n\t\t\t\t<TD width="25%">&nbsp;</TD>\r\n\t\t\t\t<TD width="50%">&nbsp;</TD>\r\n\t\t\t\t<TD width="25%">&nbsp;</TD>\r\n\t\t\t</TR>\r\n\t\t\t<TR>\r\n\t\t\t\t<TD width="25%">&nbsp;</TD>\r\n\t\t\t\t<TD width="50%">\r\n\t\t\t\t\t<TABLE style="border:2px solid black;" cellpadding=0 cellspacing=0 valign="middle" align="center" BGCOLOR="#FFFFE1" border=0>\r\n\t\t\t\t\t\t<TR><TD rowspan=3 width=20>&nbsp;&nbsp;</TD><TD>&nbsp;</TD><TD rowspan=3 width=20>&nbsp;&nbsp;</TD></TR>\r\n\t\t\t\t\t\t<TR>\r\n\t\t\t\t\t\t\t<TD>\r\n\t\t\t\t\t\t\t\t<font color=\'red\' size=3>\r\n\t\t\t\t\t\t\t\t<P>Votre navigateur Web est configur\xe9 pour ne pas ex\xe9cuter les scripts ou ne prend pas en charge les scripts dans les pages Web. V\xe9rifiez les param\xe8tres de votre navigateur ou utilisez-en un qui ex\xe9cute les scripts.</P>\r\n\t\t\t\t\t\t\t\t</font>\r\n\t\t\t\t\t\t\t</TD>\r\n\t\t\t\t\t\t</TR>\r\n\t\t\t\t\t\t<TR><TD>&nbsp;</TD></TR>\r\n\t\t\t\t\t</TABLE>\r\n\t\t\t\t</TD>\r\n\t\t\t\t<TD width="25%">&nbsp;</TD>\r\n\t\t\t</TR>\r\n\t\t\t<TR>\r\n\t\t\t\t<TD width="25%">&nbsp;</TD>\r\n\t\t\t\t<TD width="50%">&nbsp;</TD>\r\n\t\t\t\t<TD width="25%">&nbsp;</TD>\r\n\t\t\t</TR>\r\n\t\t\t</TABLE>\r\n\t\t</NOSCRIPT>\r\n\r\n\t\r\n\t<SCRIPT language="JavaScript">\r\n\tvar g_fDoFocus = true;\r\n\tfunction setFocus()\r\n\t{\r\n\t\tif (g_fDoFocus)\r\n\t\t\twindow.document.logonForm.username.focus();\r\n\t}\r\n\t</SCRIPT>\r\n\t\r\n\t</HEAD>\r\n\r\n\t<BODY scroll="AUTO" bgColor="#FFFFFF" text="#000000" onload="setFocus()">\r\n\t\t<FORM action="/exchweb/bin/auth/owaauth.dll" method="POST" name="logonForm">\r\n\t\r\n\t<INPUT type="hidden" name="destination" value="https://webmail.sonatrach.dz/exchange">\r\n\t<INPUT type="hidden" name="flags" value="0">\r\n<TABLE id="borderTable" class="standardTable" cellSpacing=0 cellPadding=0 height="100%" width="100%" bgColor="#3D5FA3" border=0>\r\n\t\t<TR height=20>\r\n\t\t\t<TD width="33%">&nbsp;</TD>\r\n\t\t\t<TD width="33%">&nbsp;</TD>\r\n\t\t\t<TD width="34%">&nbsp;</TD>\r\n\t\t</TR>\r\n\t\t<TR>\r\n\t\t\t<TD width="33%">&nbsp;</TD>\r\n\t\t\t<TD width="33%" valign="top">\r\n\t\t\t\t<TABLE id="mainTable" class="mainTable" cellSpacing=0 cellPadding=0 width=570 bgColor="#FFFFFF" border=0>\r\n\t\t\t\t\t<TR>\r\n\t\t\t\t\t\t<TD><img title="" alt="" src="/exchweb/img/spacer.gif" width="10"></TD>\r\n\t\t\t\t\t\t<TD height="100%" valign=top>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<TD width="100%" valign=top>\r\n\t\t\t\t\t\t\t<TABLE id="logoTable" dir="LTR" cellSpacing=0 cellPadding=0 width="100%" border="0" bgColor="#FFFFFF">\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<TR>\r\n\t\t\t\t\t\t\t\t\t<TD width="100%">\r\n\t\t\t\t\t\t\t\t\t\t<TABLE id="usertxtTable" width="100%" cellspacing=0 cellpadding=0 border=0 bgColor="#FFFFFF">\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<TR><TD noWrap align="left" valign="top" height="8">&nbsp;</TD><TD width=10 rowspan=2>&nbsp;</TD></TR>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t<TR>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<TD VALIGN=top>\r\n<table id="contentTable" style="background: url(\'/exchweb/img/1.gif\')" width="100%" height=\'100%\' cellpadding=0 cellspacing=0 border="0">\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  \r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td nowrap width="13%"><p>\r\n      <label for="username">&nbsp;&nbsp;</label>\r\n    </p></td>\r\n    <td width="7%" rowspan=15>&nbsp;&nbsp;</td>\r\n    <td width="27%" >Domaine\\Nom d\'utilisateur :</td>\r\n    <td width="32%" ><input type="text" id="username" name="username" style="width:85%" size="15" maxlength="200" /></td>\r\n    <td width="1%" rowspan=12>&nbsp;&nbsp;</td>\r\n    <td width="20%" align="right">&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td height="5"></td>\r\n    <td height="5" colspan="2" valign="top"><img title="" alt="" src="/exchweb/img/spacer.gif" width=20 height=5></td>\r\n    <td height=5></td>\r\n  </tr>\r\n  <tr>\r\n    <td width="13%" nowrap><p>\r\n      <label for="password">&nbsp;&nbsp;</font></label>\r\n    </p></td>\r\n    <td width="27%" >Mot de passe :</td>\r\n    <td width="32%" ><input type="password" autocomplete="off" style="width:85%" id="password" name="password" size="25" maxlength="256" onfocus="g_fDoFocus=false;" /></td>\r\n    <TD width="20%"><INPUT type="submit" value="Se connecter" id="SubmitCreds" name="SubmitCreds"></TD>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD height="12"></TD>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD height="12" colspan="2" valign="top"><img title="" alt="" src="/exchweb/img/spacer.gif" width=25 height=12></TD>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TD height=12></TD>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<TR><TD>&nbsp;</TD><TD colspan=4><TABLE cellspacing=0 cellpadding=0 border=0><TR><TD colspan=2 width="100%" style="padding-bottom:3px;"><B>S\xe9curit\xe9</B>&nbsp;</TD></TR><TR><TD colspan="2"><TABLE cellspacing=0 cellpadding=0><TR><TD><INPUT id="rdoPublic" checked type="radio" name="trusted" value="0" onclick="flags.value &= 11"></TD><TD NOWRAP><LABEL for="rdoPublic">Ordinateur public ou partag\xe9</LABEL></TD></TR><TR><TD height=6><img title="" alt="" src="/exchweb/img/spacer.gif" height=6></TD><TD height=6></TD></TR><TR id="trPublic"><TD>&nbsp;</TD><TD>S\xe9lectionnez cette option si vous utilisez Microsoft Outlook Web Access sur un ordinateur public.</TD></TR></TABLE></TD></TR><TR><TD height=6><img title="" alt="" src="/exchweb/img/spacer.gif" height=6></TD><TD height=6></TD></TR><TR><TD colspan="2"><TABLE cellspacing=0 cellpadding=0><TR><TD><INPUT id="rdoTrusted" name="trusted" type="radio" value="4" onclick="flags.value |= 4"></TD><TD NOWRAP><LABEL for="rdoTrusted">Ordinateur priv\xe9</LABEL></TD></TR><TR><TD height=6><img title="" alt="" src="/exchweb/img/spacer.gif" height=6></TD><TD height=6></TD></TR><TR id="trTrusted"><TD>&nbsp;</TD><TD>S\xe9lectionnez cette option si vous \xeates la seule personne \xe0 utiliser cet ordinateur.</TD></TR><TR id="trWrn"><TD>&nbsp;</TD><TD><FONT color="red"><B>Avertissement :</B> si vous s\xe9lectionnez cette option, vous reconnaissez que l\'ordinateur est conforme aux r\xe8gles de s\xe9curit\xe9 de votre entreprise.</FONT></TD></TR></TABLE></TD></TR></TABLE></TD></TR>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</TABLE>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</TD>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</TR>\r\n\t\t\t\t\t\t\t\t\t\t\t</TABLE>\r\n\t\t\t\t\t\t\t\t\t\t</TD>\r\n\t\t\t\t\t\t\t\t\t</TR>\r\n\t\t\t\t\t\t\t\t\t<TR><TD colspan=2 width="100%">&nbsp;</TD></TR>\r\n\t\t\t\t\t\t\t\t</TABLE>\r\n\t\t\t\t\t\t\t</TD>\r\n\t\t\t\t\t\t</TR>\r\n\t\t\t\t</TABLE>\r\n\t\t\t\t\t<DIV dir="LTR" >\r\n\t\t\t\t\t<FONT color="#FFFFFF">\r\n\t\t\t\t\t\t<BR>\r\n\t\t\t\t\t\tPour emp\xeacher que des personnes non autoris\xe9es n\'acc\xe8dent \xe0 votre compte, Microsoft Outlook Web Access ferme automatiquement la connexion qu\'il a \xe9tablie avec votre bo\xeete aux lettres au bout d\'une certaine p\xe9riode d\'inactivit\xe9. Si la session venait \xe0 se terminer, actualisez votre navigateur et connectez-vous \xe0 nouveau.\r\n\t\t\t\t\t</FONT>\r\n\t\t\t\t</DIV>\r\n\t\t\t</TD>\r\n\t\t\t<TD width="34%">&nbsp;</TD>\r\n\t\t</TR>\r\n\t\t<TR>\r\n\t\t\t<TD width="33%">&nbsp;</TD>\r\n\t\t\t<TD width="33%">&nbsp;</TD>\r\n\t\t\t<TD width="34%">&nbsp;</TD>\r\n\t\t</TR>\r\n</TABLE>\r\n\r\n\r\n\r\n\r\n\t\r\n\t</FORM>\r\n\t</BODY>\r\n\r\n</HTML>\r\n', 2074, 2075, 'invalid continuation byte')
Error UID: 5939f557-d730-4f52-9a7a-62d030d5c4a1
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.2.0-beta
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 2.7.11
Gtk Version: 3.18.6
Timezone: Africa/Algiers

Thread Information:
 => MainThread (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/web_cloner.py", line 275, in cb_get_data_finish
    self.copy_resource_data(resource, data)
  File "/usr/share/king-phisher/king_phisher/client/web_cloner.py", line 185, in copy_resource_data
    data = codec.decode(data)[0]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 2074: invalid continuation byte

```

**Comment by zeroSteiner** [comment]
This seems to be an issue with a invalid or no encoding information being provided. I addressed this issue in commit 56aff98 by catching exceptions while decoding data in the patch_html routine. If this fails, the KP js will not be patched in but the content will otherwise continue to function.
